import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin } from 'react-icons/ai';
import deved from "../public/ReadyPlayerMe-Avatar.png";
import Image from "next/image";
import design from '../public/figma-dynamic-color.png'
import code from '../public/code.png'
import consulting from '../public/computer-dynamic-color.png'
import web1 from "../public/web1.jpg";
import web2 from "../public/web2.jpg";
import web3 from "../public/web3.jpg";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Luis Guzman Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl dark:text-white'>Developed By Luis</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' /></li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="../public/guzman-resume.pdf" download={"Luis-Guzman.pdf"}>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Luis Guzman</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Computer Science Engineering</h3>
            <p className='text-md py-5 leading-8 text-gray-800 mx-auto md:text-xl max-w-xl dark:text-white'>Graduated of Bachelor s Degree in Computer Science with knowledge of software development and design.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://www.linkedin.com/in/luis-guzm%C3%A1n-b29322177/"><AiFillLinkedin /></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover' alt={''} />
          </div>
          <section>
            <div>
              <h3 className='text-3xl py-1 dark:text-white'>Tools I Work with...</h3>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>

              </p>
            </div>
            <div className='lg:flex gap-10'>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-white flex-1">
                <Image src={design} width={100} height={100} alt={''} style={{
                  margin: "auto",
                }} />
                <h3 className='text-lg font-medium pt-8 pb-2'>Beatiful User Interface Design</h3>
                <p className='py-2'>
                  Creating elegant and suited designs for you
                </p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className='text-gray-800 py-1'>Figma</p>
                <p className='text-gray-800 py-1'>Photoshop</p>
                <p className='text-gray-800 py-1'>AI</p>
              </div>
              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-white flex-1">
                <Image src={consulting} width={100} height={100} alt={''} style={{
                  margin: "auto",
                }} />
                <h3 className='text-lg font-medium pt-8 pb-2'>IDEs I Work With</h3>
                <p className='py-2'>
                  Integrated development environment Software / programming
                </p>
                <h4 className='py-4 text-teal-600'>IDE I use</h4>
                <p className='text-gray-800 py-1'>Visual Studio Code</p>
                <p className='text-gray-800 py-1'>Eclipse</p>
                <p className='text-gray-800 py-1'>Andriod Studio</p>
              </div>

              <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-white flex-1">
                <Image src={code} width={100} height={100} alt={''} style={{
                  margin: "auto",
                }} />
                <h3 className='text-lg font-medium pt-8 pb-2'>My Programming Languages</h3>
                <p className='py-2'>
                  Creating elegant designs suited for you...
                </p>
                <h4 className='py-4 text-teal-600'> Languages I use</h4>
                <p className='text-gray-800 py-1'>Java</p>
                <p className='text-gray-800 py-1'>JavaScript</p>
                <p className='text-gray-800 py-1'>Dart</p>
              </div>
            </div>
          </section>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portafolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Since the beginning of my journey in my career, I have done some projects working with frameworks such as react, flutter and spring, also
              my I have knowledge in Java, Dart, HTML, CSS and Javascript.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/4 flex-1'>
              <Image src={web1} alt="" className='rounded-lg object-cover' layout='responsive' />
            </div>
            <div className='basis-1/4 flex-1'>
              <Image src={web2} alt="" className='rounded-lg object-cover' layout='responsive' />
            </div>
            <div className='basis-1/4 flex-1'>
              <Image src={web3} alt="" className='rounded-lg object-cover' layout='responsive' />
            </div>
          </div>
        </section>
        <section>
          <h3 className='text-3xl py-1 dark:text-white'>Certifications</h3>
          <a href="https://simpli-web.app.link/e/k0nQDHL2Avb"><h3 className='py-4 text-teal-600 text-2xl'>Java Certification Course</h3></a>
          <a href="https://www.udemy.com/certificate/UC-55297d5b-1b76-4527-a1b0-a5fd1ef9512d/" ><h3 className='py-4 text-teal-600 text-2xl'>Java Programming: Complete Beginner to Advanced</h3></a>
          <a href="https://www.freecodecamp.org/certification/fccffbd99d5-0dd9-45b0-81fa-f86716719558/responsive-web-design"><h3 className='py-4 text-teal-600 text-2xl'>Responsive Web Design</h3></a>
          <a href="https://platzi.com/p/LuisGuzman2535/curso/1474-oop/diploma/detalle/"><h3 className='py-4 text-teal-600 text-2xl'>PROGRAMACIÓN ORIENTADA A OBJETOS</h3></a>
          <a href="https://platzi.com/p/LuisGuzman2535/curso/1814-basico-javascript/diploma/detalle/"><h3 className='py-4 text-teal-600 text-2xl'>JAVASCRIPT</h3></a>
        </section>
      </main>
    </div >
  )
}
